import {
    AccdbFileIcon,
    DocxFileIcon,
    ImageFileIcon,
    PdfFileIcon,
    PptxFileIcon,
    XlsxFileIcon,
    TextFileIcon,
    ArchiveFileIcon,
    VideoFileIcon,
    AudioFileIcon,
} from 'assets';

export const ICON_BY_FILE_TYPE: Record<
    string,
    React.FunctionComponent<
        React.SVGProps<SVGSVGElement> & {
            title?: string | undefined;
        }
    >
> = {
    '.accdb': AccdbFileIcon,
    '.doc': DocxFileIcon,
    '.docx': DocxFileIcon,
    '.odg': DocxFileIcon,
    '.png': ImageFileIcon,
    '.jpg': ImageFileIcon,
    '.jpeg': ImageFileIcon,
    '.svg': ImageFileIcon,
    '.eps': ImageFileIcon,
    '.ai': ImageFileIcon,
    '.gif': ImageFileIcon,
    '.tiff': ImageFileIcon,
    '.bmp': ImageFileIcon,
    '.webp': ImageFileIcon,
    '.heif': ImageFileIcon,
    '.heic': ImageFileIcon,
    '.psd': ImageFileIcon,
    '.xcf': ImageFileIcon,
    '.indd': ImageFileIcon,
    '.pdf': PdfFileIcon,
    '.ppt': PptxFileIcon,
    '.pptx': PptxFileIcon,
    '.xls': XlsxFileIcon,
    '.xlsx': XlsxFileIcon,
    '.txt': TextFileIcon,
    '.py': TextFileIcon,
    '.js': TextFileIcon,
    '.jsx': TextFileIcon,
    '.css': TextFileIcon,
    '.scss': TextFileIcon,
    '.styl': TextFileIcon,
    '.pcss': TextFileIcon,
    '.postcss': TextFileIcon,
    '.less': TextFileIcon,
    '.html': TextFileIcon,
    '.ts': TextFileIcon,
    '.tsx': TextFileIcon,
    '.json': TextFileIcon,
    '.xml': TextFileIcon,
    '.java': TextFileIcon,
    '.cs': TextFileIcon,
    '.c': TextFileIcon,
    '.cpp': TextFileIcon,
    '.sql': TextFileIcon,
    '.asm': TextFileIcon,
    '.php': TextFileIcon,
    '.rb': TextFileIcon,
    '.rs': TextFileIcon,
    '.7z': ArchiveFileIcon,
    '.zip': ArchiveFileIcon,
    '.rar': ArchiveFileIcon,
    '.zipx': ArchiveFileIcon,
    '.s7z': ArchiveFileIcon,
    '.bz2': ArchiveFileIcon,
    '.gz': ArchiveFileIcon,
    '.mp4': VideoFileIcon,
    '.mov': VideoFileIcon,
    '.avi': VideoFileIcon,
    '.wmv': VideoFileIcon,
    '.m2ts': VideoFileIcon,
    '.flv': VideoFileIcon,
    '.f4v': VideoFileIcon,
    '.swf': VideoFileIcon,
    '.mkv': VideoFileIcon,
    '.webm': VideoFileIcon,
    '.mpg': VideoFileIcon,
    '.mp3': AudioFileIcon,
    '.m4a': AudioFileIcon,
    '.aac': AudioFileIcon,
    '.ogg': AudioFileIcon,
    '.oga': AudioFileIcon,
    '.wav': AudioFileIcon,
    '.flac': AudioFileIcon,
    '.pcm': AudioFileIcon,
    '.aif': AudioFileIcon,
};
